apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd
spec:
  description: Business applications (web, core)
  sourceRepos:
    - https://github.com/RevieU-Corp/revieu-infra.git
    - https://github.com/RevieU-Corp/revieu-backend.git
  destinations:
    - namespace: 'revieu-*'
      server: https://kubernetes.default.svc
    - namespace: 'argocd'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: 'argoproj.io'
      kind: Application
    - group: 'apps'
      kind: Deployment
    - group: 'apps'
      kind: StatefulSet
    - group: ''
      kind: Service
    - group: 'networking.k8s.io'
      kind: Ingress
    - group: 'traefik.io'
      kind: IngressRoute
    - group: 'traefik.io'
      kind: Middleware
    - group: 'cert-manager.io'
      kind: Certificate
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: 'bitnami.com'
      kind: SealedSecret
  orphanedResources:
    warn: true
