apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../prod/infrastructure/fluent-bit
  - ../../../prod/infrastructure/loki
  - ../../../prod/infrastructure/grafana
  - ../../../prod/infrastructure/prometheus
