---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-credentials
  namespace: revieu-dev
spec:
  encryptedData:
    .dockerconfigjson: AgAMLy6YGOpouufCE3cPWddWh8K7LxembCWVyV2GTKhklAdJRjcRt+j18EdSRK86JMhjjqXW9B/8MQPTI1DkVysh3GSa8CV0MYy+wmuEeG6jAQ+Um1049qXivK1EJAZO8Fcfdk7qAM2GuJYKv05GRz0O79Ek0uzEhnEXJoiBHA3XOCU936mP2FLZujJymINngy3PrSmgcUsAfYfgcqBHApzbixsGv8IRpCu5lbEblY84SU4EJmr0Yw7bCLD8k8SH2YugcMoCNCFffSwxvfo5zMNFPEuB/SYfoVE4qqJrUH+XM+o13pDoB8tWtYhgWjyTPuKKJ2gp+y3dhfL7CjVa7aAz/ADitdAOdMljXGaig+IokLhEopA8EquhXTOvKVzfPiJIwkpkLZBpGI9kofV+B+2cb/aUW3a0KcNBWdRHNRa5xDDy+nd7or87kc7SJH/o4XDzbPTQjsImSKXomE33EEWs3/aRVF87K51x5/0hPfaM2wHly4zDsQOi44Ns4dtv7TV43d1VFFiUOQNHB/AetWoKOZ7ZrRg8rS1V9YzRx69jpqF9wZ8fNZzQYY70HhB8ChvGCW7MW7Y3cp9vnpxI2AbPwtx95BrWzZwq/4oDtJzhQqhNvKJzKH2uWDDTL67bcJQ88EKDZ3ykhbleVSvAYlm8ofCDyhON/+r/QyX9EE/xOYavB4GfUwtDaFApCpGrJKu42ys+ER0kTbVvAhCMHNQPGgwxmhERjFMnbWJ0lXxWFPHOXeVVvDRBNm7XtvkRuGWiA7NSKECF8T8KqF8qAqqrv6rxIumjxqUMtsiB82TbdRRF/oLCNXL+1gQ+1ZHtSl8Kls4J4eA1F45Y8A1Gh51x+h7+zjxdg3wpjA111yEJ0Q85Na/OqCecfmalfyABLMkINlwaa/DIyYftIYC/ZMBVmqtcxgFZdlXIYw+NVEEDDxUhUWA9yvyH/4WKqe3wlYkJNbrhwgt56jtYYnc5aoVRKi0VkdSw7gOdhKreODk=
  template:
    metadata:
      name: ghcr-credentials
      namespace: revieu-dev
    type: kubernetes.io/dockerconfigjson
