apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: revieu-core-secrets-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  labels:
    app.kubernetes.io/name: core-secrets
    app.kubernetes.io/component: backend
    environment: development
spec:
  project: applications
  source:
    repoURL: https://github.com/RevieU-Corp/revieu-backend.git
    targetRevision: main
    path: apps/core/configs
    directory:
      include: sealed-secrets-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: revieu-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        maxDuration: 2m
