apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/applications/web

namespace: revieu-dev

images:
  - name: ghcr.io/revieu-corp/revieu-web
    newTag: sha-2afcaa4

patches:
  - target:
      kind: Deployment
      name: revieu-web
    patch: |-
      - op: add
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            memory: "128Mi"
          limits:
            memory: "256Mi"

  - target:
      kind: Ingress
      name: revieu-web-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.revieu.weijun.online
      - op: replace
        path: /spec/tls/0/hosts/0
        value: dev.revieu.weijun.online
