apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/apps/web

images:
  - name: ghcr.io/revieu-corp/revieu-web
    newTag: sha-62dc89d # 具体的版本号

patches:
  - target:
      kind: Deployment
      name: revieu-web
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
