apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Dev 环境主入口
resources:
  - ./common
  - ./applications/web
  - ./applications/core
  - ./infrastructure

namespace: revieu-dev  # Dev 环境命名空间
