apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: revieu-cert
  namespace: revieu-prod
spec:
  secretName: revieu-web-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "revieu.weijun.online"
