apiVersion: apps/v1
kind: Deployment
metadata:
  name: revieu-auth
spec:
  # replicas: 同样留给 overlays
  selector:
    matchLabels:
      app: revieu-auth
  template:
    metadata:
      labels:
        app: revieu-auth
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: auth
          image: ghcr.io/revieu-corp/revieu-auth-service # 对应后端容器
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: revieu-auth-config
            - configMapRef:
                name: revieu-auth-env-config
            - secretRef:
                name: revieu-auth-secret
