apiVersion: v1
kind: Secret
metadata:
  name: revieu-auth-secret
type: Opaque
stringData:
  JWT_SECRET_KEY: "placeholder"
  POSTGRES_USER: "placeholder"
  POSTGRES_PASSWORD: "placeholder"
  MAIL_USERNAME: "placeholder"
  MAIL_PASSWORD: "placeholder"
  GOOGLE_CLIENT_ID: "placeholder"
  GOOGLE_CLIENT_SECRET: "placeholder"
  GITHUB_CLIENT_ID: "placeholder"
  GITHUB_CLIENT_SECRET: "placeholder"
