apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/applications/core
  - https://raw.githubusercontent.com/RevieU-Corp/revieu-backend/refs/heads/main/apps/core/configs/sealed-secrets-dev.yaml

namespace: revieu-dev

images:
  - name: ghcr.io/revieu-corp/revieu-core
    newTag: sha-20fc7ca

patches:
  - target:
      kind: Deployment
      name: revieu-core
    patch: |-
      - op: add
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            memory: "256Mi"
          limits:
            memory: "512Mi"

  - target:
      kind: Ingress
      name: revieu-core-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.revieu.weijun.online
      - op: replace
        path: /spec/tls/0/hosts/0
        value: dev.revieu.weijun.online
