apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/applications/core/

images:
  - name: ghcr.io/revieu-corp/revieu-core
    newTag: sha-ee15138 # Updated: WireGuard DB config + env vars
