apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# cert-manager 官方 manifest，适用于任何 k8s 集群
resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.17.0/cert-manager.yaml
