apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/namespace.yaml
  - ../../../base/cluster-issuer.yaml
  - ../../../base/postgres-external
  - ../../../base/traefik-auth-middleware.yaml

patches:
  - target:
      kind: ClusterIssuer
      name: letsencrypt-prod
    patch: |-
      - op: replace
        path: /spec/acme/email
        value: liweijun0302@gmail.com
