apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: revieu-core-ingress
  namespace: revieu-prod
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  tls:
    - hosts:
        - revieu.weijun.online
      secretName: revieu-tls-cert
  rules:
    - host: revieu.weijun.online
      http:
        paths:
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: revieu-core-service
                port:
                  number: 8080
