---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-credentials
  namespace: revieu-prod
spec:
  encryptedData:
    .dockerconfigjson: AgBXpENzbDMOUZ78+lTrZ3sk+6cuXIy2kiVhZJ341SCY5Q19ldBxmRegvElD8j1+hNMEe1Ual/XMZ2fpu/LmptfoLR3uWHjlwidTFipW5H5muQ9xm2ONjoiSsZ+Vm4f1zduB24Zm4UCKbDKnnxVthgYPl2yNDJkbVox+xhAdYSK1YNx5XhDc0aQRXXDNy0CGsdsEY4zsVu0Q52lKgWKl4PTHC0Scw9xqr2FqieUkAhfcMm6ML2n33EkVjo8PeNI6Oksar84R3inz4OTCOIJUHFD8UNUmKKmw8NMAwjknPjzPiDH9N8um6se9tXzgQImynkv9tN4vZaiq8VNKJSzD4tk32hXB4d6Go/WZ1k6eDw0RdgsGNCgmVXoeVJeXLutIO0yF9wyTl4+oQe4Nf1PmaDos/A9dfzPQzon/P3CVSvKKEnzL++H+AdvnB72H2rNheG1vMhBHuBUGW+jRE0rp3pRGYKhk6101QlQmreAt+6d/u7WP02SWDbYfVX6Z2p4ix7wDpaCd1Kn1v3cUG5TehdW4U1BvJgRrSKmKhNjGfGLG+6evSlcNWgzd0hcwQn5NBeKsoyaVah12hkf3BxZju/RK2mTW094MwlIbeEGsS3c+OmRK+LCUYuWWGP9ZfD37txW+c08FxuiBp5+anNPe+7pPQpT604X3R0IrK1R4bn6N9eNOkw7qdHHEk85oQwX3KbLurjOfDFDrXxG6cn5+TIb70BPVLuDDh/7M7hcESPjyjkdtmIiDHYGEtfDHeD23/yaUjl1HejG76blF/1Y2cOxhBQ4Ef1KAEPmVQeFxQK9YoVpj+6c10nMaWolu9sOoew1a9IWZJpJzZ7kziclxHSAiNJ9C+gbypNoBxZ90VhX2c35EeYaEsHA1kgVm4wPUiaGNcyJwCH2o2eQK9uFKdbdwlXwyGQ4vHCt8S1a3s/vxZ8NSNx/i4LmQzLLa8yjeIpB4ou/lRBhumPLp8J1o1kauoDRnJ4yoc0EHC3S8+78=
  template:
    metadata:
      name: ghcr-credentials
      namespace: revieu-prod
    type: kubernetes.io/dockerconfigjson
