---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-credentials
  namespace: revieu-prod
spec:
  encryptedData:
    .dockerconfigjson: AgBvorA2R1EemqlVbH0TFrNivDNbcHQrVRTX/qvCoh/YSY+YlvAHF8svVfsCOFqMXoho0aU7lbSVbwc9nRTm9LuYVRnEGazod23x00h9jFMoeVFiQHgB1Z7d1cDCyEoWw4aH/5mdIh/x74AGOg3VVI5fhpNkEZpNxPqoXmwk0Ir9O8viPy1Ozsw66UuU28qySmrxN/nY7xueqROsi8VAH+nY+FFx7QmL/XY1xO9Uq73XIId/Kdp+322mD/4gW+Zm6dpThNX5vLggDdygUmF0dVnmwaDfOdM4vOLwOtfF5gvzx/XUsx7Abx0OHXrZdBgyUA6xw605ZyVVYm2yJ3fJeXLXN4Q9rX76CjLy/w0Q9SyheDmmbcBLvk1Yy3Sk4VBzphyMiGTYPrQ+ZmPA4Cm/jkufm4LaM2ti1nu1U0UKSg1LfmB+2jQZWFbs/XK5HxYT5JQL+/8UNoE3BUcBoOO4xVrYcT3QglHSl11UJLdJhjkJzGoBnG3ouqW2Nc9qJR28mkDMzy41hGJRCmQsdgMecX9Qh0f3Lzi/zMWJ+//bkzY2YvjvXAi2APDDXGDt6PDrFhY5Cj6NREAPGbhfesu7mR1VVKlEkJIyN2m7iAl+Kro/femhx4f40bq5E3a0FdCYdL8UL2uiAs4Oe6LGGoYY6qUdbJayQ3Yc+6tc5AeU4tj35Ere6xVltxDXapV1ebA3ajOoPHP8Rjh+LqI/WcUH92rPPeYG+uwaIVMUuZmHKPhREsjL6tWUpIX1PSL3+Fcyupnp6reuTaAmK+bWpZpXfZ/KMkRwP08DNHKNpBDrQ6XBMe6Q6LEY/WC2nbQzYjOkEYyCHjbPitLKUJC5jAzkMYt+fdwzQ04SF76AFY8hlaY4IPTl0WD3KMXnZRw6lkzAjUSrXcklEK1/1dOVuI0KI7yW7QHV4RuIcH1apHkDpOqMWE0qEXOgs1JZotbuBtlxnSR72CPdT4VOPiW3gup5ldYzkJIS7KlE33nEmoXr+vM8XSkL
  template:
    metadata:
      name: ghcr-credentials
      namespace: revieu-prod
    type: kubernetes.io/dockerconfigjson
