apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/common/namespace.yaml
  - ../../../base/common/certificate.yaml
  - cloudflare-api-token-sealed.yaml
  - ghcr-credentials-sealed.yaml
