apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: revieu-web-ingress
  namespace: revieu-prod
  annotations:
    # 只要这一个注解就够了，告诉 K8s 这个 Ingress 归 APISIX 管
    kubernetes.io/ingress.class: apisix
    # 不需要 cert-manager 的注解了，因为我们上面单独定义了 Certificate
spec:
  # ingressClassName: apisix # 新版 K8s 推荐留着这个，双重保险
  tls:
    - hosts:
        - revieu.weijun.online
      secretName: revieu-web-tls-secret # 【重点】引用上面 Certificate 生成的 Secret
  rules:
    - host: revieu.weijun.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: revieu-web-service # 你的 Service 名字
                port:
                  number: 80
