apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: revieu-web-ingress
  annotations:
    # 1. 声明这是 APISIX 的 Ingress
    kubernetes.io/ingress.class: apisix
    # 2. 告诉 Cert-manager 用哪个 Issuer (前面步骤创建的)
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # 3. (可选) 开启 HTTP 自动跳转 HTTPS
    k8s.apisix.apache.org/http-to-https: "true"
spec:
  tls:
    - hosts:
        - revieu.weijun.online # 你的域名
      secretName: revieu-web-tls-secret # 证书会自动存到这里
  rules:
    - host: revieu.weijun.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: revieu-web-service # 对应上面创建的 Service 名字
                port:
                  number: 80 # 对应 Service 的 port
