apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-core-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: platform
  source:
    repoURL: https://github.com/RevieU-Corp/revieu-infra.git
    targetRevision: main
    path: apps/overlays/prod/common
  destination:
    server: https://kubernetes.default.svc
    namespace: revieu-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
