apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/apps/core
  - https://raw.githubusercontent.com/RevieU-Corp/revieu-backend/37858c6/apps/core/configs/sealed-secrets.yaml

images:
  - name: ghcr.io/revieu-corp/revieu-core
    newTag: sha-37858c6 # Updated: WireGuard DB config + env vars
