apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # 默认占位符，建议在 overlays 中通过 patch 覆盖
    email: admin@example.com
    # Let's Encrypt 生产环境服务器
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # 存储账号私钥的 Secret 名称（自动生成，不用管）
      name: letsencrypt-prod-account-key
    solvers:
      - http01:
          ingress:
            # 指定 ingress class 为 traefik
            class: traefik
