apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kibana-cert
spec:
  secretName: kibana-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "kibana.weijun.online"
