apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/apps/auth
  - sealed-auth-secrets.yaml

images:
  - name: ghcr.io/revieu-corp/revieu-auth-service
    newTag: sha-bcaf199 # 对应 auth 的版本号

      #secretGenerator:
      #  - name: revieu-auth-secret
      #    envs:
      #      - secrets.env
