apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Main entry point for production
# Grouped by service/component for better organization
resources:
  - ./common
  - ./apps/core
  - ./apps/web
  - ./external/postgres
  - ./middleware
