apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Main entry point for production
# Grouped by service/component for better organization
resources:
  - ./common
  - ./apps/auth
  - ./apps/web
  - ./apps/elasticsearch
  - ./external/postgres
  - ./middleware

# Global Namespace
namespace: revieu-prod
